// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpkhvswaldmeaxuogrhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwa2h2c3dhbGRtZWF4dW9ncmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Njk0NDYsImV4cCI6MjA2MjU0NTQ0Nn0.7Rx-CU9BAO_CQWglBXlRZ1RnKGvHTaKbJL8KG5__jY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);